export const dosNc = {
  id: 'dos-nc',
  name: 'DOS / Norton Commander',
  tokens: {
    '--bg-base': '#0000AA',
    '--bg-raised': '#0000AA',
    '--bg-sunken': '#000000',
    '--panel-surface': '#0000AA',
    '--panel-header': '#00AAAA',
    '--border-subtle': '#00AAAA',
    '--border-strong': '#55FFFF',
    '--text-primary': '#55FFFF',
    '--text-secondary': '#00AAAA',
    '--text-muted': '#AAAAAA',
    '--accent': '#FFFF55',
    '--accent-strong': '#FFFF55',
    '--accent-dim': '#AA5500',
    // Graph pulse/particle colour. Must differ from every node base colour
    // (--accent, --accent-secondary, --text-secondary) or a lit node fades to
    // exactly its own colour and nothing appears to happen.
    '--graph-pulse': '#FFFFFF',
    '--accent-secondary': '#55FF55',
    '--focus-ring': '#FFFFFF',
    '--danger': '#FF5555',
    '--bg-base-rgb': '0, 0, 170',
    '--bg-sunken-rgb': '0, 0, 0',
    '--panel-surface-rgb': '0, 0, 170',
    '--panel-header-rgb': '0, 170, 170',
    '--font-ui': "'Px437 IBM VGA', Consolas, monospace",
    '--radius-lg': '0',
    '--radius-md': '0',
    '--radius-sm': '0',
    '--glow-active': 'none',
    '--glow-dot': 'none',
  },
  terminalFont: { fontFamily: "'Px437 IBM VGA', Consolas, monospace", fontSize: 16 },
  terminal: {
    background: '#000000',
    foreground: '#AAAAAA',
    cursor: '#AAAAAA',
    cursorAccent: '#000000',
    selectionBackground: '#00AAAA',
    black: '#000000', red: '#AA0000', green: '#00AA00', yellow: '#AA5500',
    blue: '#0000AA', magenta: '#AA00AA', cyan: '#00AAAA', white: '#AAAAAA',
    brightBlack: '#555555', brightRed: '#FF5555', brightGreen: '#55FF55',
    brightYellow: '#FFFF55', brightBlue: '#5555FF', brightMagenta: '#FF55FF',
    brightCyan: '#55FFFF', brightWhite: '#FFFFFF',
  },
};
